<?php
/**
 * TL_ROOT/system/modules/isotope/languages/de/default.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['tableExists'] = "Tabelle `%s` existiert schon. Bitte wählen Sie einen andere Tabelle aus.";
$GLOBALS['TL_LANG']['ERR']['tableDoesNotExist'] = "Tabelle `%s` existiert noch nicht.";
$GLOBALS['TL_LANG']['ERR']['columnExists'] = "Spalte `%s` existiert schon. Bitte wählen Sie eine andere Spalte aus.";
$GLOBALS['TL_LANG']['ERR']['columnDoesNotExist'] = "Spalte `%s` existiert noch nicht in Tabelle %s.";
$GLOBALS['TL_LANG']['ERR']['systemColumn'] = "Name `%s` ist für das System reserviert. Bitte wählen Sie einen anderen Namen aus.";
$GLOBALS['TL_LANG']['ERR']['invalidColumnName'] = "Ungültiger Spaltenname `%s`. Bitte verwenden Sie nur Buchstaben, Nummern und den Unterstrich.";
$GLOBALS['TL_LANG']['ERR']['invalidTableName'] = "Ungültiger Tabellenname `%s`. Bitte verwenden Sie nur Buchstaben, Nummern und den Unterstrich.";
$GLOBALS['TL_LANG']['ERR']['aliasTitleMissing'] = "Ungültige Alias-Feld-Konfiguration. Fehlende Titel-Feld-Parameter.";
$GLOBALS['TL_LANG']['ERR']['aliasDuplicate'] = "Alias-Feld `%s` wurde schon definiert. Nur ein Alias-Feld ist pro Tabelle erlaubt.";
 
?>
