<?php
/**
 * TL_ROOT/system/modules/isotope/languages/de/modules.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['catalog']['0'] = "Katalog";
$GLOBALS['TL_LANG']['MOD']['catalog']['1'] = "Dieses Modul erlaubt es Ihnen einen Katalog mit Einträgen zu verwalten.";
$GLOBALS['TL_LANG']['FMD']['catalogListing']['0'] = "Katalog-Liste";
$GLOBALS['TL_LANG']['FMD']['catalogListing']['1'] = "Benutzen Sie dieses Modul, um Katalog-Einträge im Frontend aufzulisten.";
 
?>
