<?php
/**
 * TL_ROOT/system/modules/isotope/languages/de/tl_catalog_items.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_items']['export']['0'] = "CSV Export";
$GLOBALS['TL_LANG']['tl_catalog_items']['export']['1'] = "Einträge in eine CSV-Datei exportieren";
$GLOBALS['TL_LANG']['tl_catalog_items']['new']['0'] = "Neuer Eintrag";
$GLOBALS['TL_LANG']['tl_catalog_items']['new']['1'] = "Neuen Eintrag erstellen";
$GLOBALS['TL_LANG']['tl_catalog_items']['edit']['0'] = "Eintrag bearbeiten";
$GLOBALS['TL_LANG']['tl_catalog_items']['edit']['1'] = "Eintrag ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_catalog_items']['copy']['0'] = "Eintrag kopieren";
$GLOBALS['TL_LANG']['tl_catalog_items']['copy']['1'] = "Eintrag ID %s kopieren";
$GLOBALS['TL_LANG']['tl_catalog_items']['cut']['0'] = "Eintrag verschieben";
$GLOBALS['TL_LANG']['tl_catalog_items']['cut']['1'] = "Eintrag ID %s verschieben";
$GLOBALS['TL_LANG']['tl_catalog_items']['delete']['0'] = "Eintrag löschen";
$GLOBALS['TL_LANG']['tl_catalog_items']['delete']['1'] = "Eintrag ID %s löschen";
$GLOBALS['TL_LANG']['tl_catalog_items']['show']['0'] = "Eintrags-Eigenschaften";
$GLOBALS['TL_LANG']['tl_catalog_items']['show']['1'] = "Eigenschaften des Eintrags ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_catalog_items']['editheader']['0'] = "Eintragstyp bearbeiten";
$GLOBALS['TL_LANG']['tl_catalog_items']['editheader']['1'] = "Eintragstyp bearbeiten";
 
?>
