<?php
/**
 * TL_ROOT/system/modules/isotope/languages/de/tl_catalog_fields.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_fields']['name']['0'] = "Bezeichnung";
$GLOBALS['TL_LANG']['tl_catalog_fields']['name']['1'] = "Die Feldbezeichnung wird verwendet, um das Feld zu beschreiben.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_catalog_fields']['description']['1'] = "Feldbeschreibung. Wird unter dem Eingabefeld angezeigt, um eine Hilfe oder eine Beschreibung des Feldes zu liefern.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['colName']['0'] = "Spaltenname";
$GLOBALS['TL_LANG']['tl_catalog_fields']['colName']['1'] = "Name der Spalte in der Datenbanktabelle.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['type']['0'] = "Typ";
$GLOBALS['TL_LANG']['tl_catalog_fields']['type']['1'] = "Feldtyp.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['titleField']['0'] = "Titel-Feld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['titleField']['1'] = "Falls angehakt, wird der Feldwert als Eintragstitel betrachtet und in der Listenansicht angezeigt.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['aliasTitle']['0'] = "Alias-Titel-Feld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['aliasTitle']['1'] = "Bitte wählen Sie das Titel-Feld aus, das für die Auto-Erstellung des Alias verwendet werden soll.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filteredField']['0'] = "Filter";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filteredField']['1'] = "Falls angehakt, können Sie angezeigte Einträge abhängig vom Feldwert im TL Backend filtern.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['insertBreak']['0'] = "Vorher Umbruch einfügen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['insertBreak']['1'] = "Erstellt einen Umbruch zwischen den Feldern zur besseren optischen Gruppierung.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['searchableField']['0'] = "Suche";
$GLOBALS['TL_LANG']['tl_catalog_fields']['searchableField']['1'] = "Falls angehakt, können Sie nur angezeigte Einträge suchen lassen, die bestimmte Suchkriterien im TL Backend erfüllen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['sortingField']['0'] = "Sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['sortingField']['1'] = "Falls angehakt, können Sie ausgehend von diesem Feld angezeigte Einträge im TL Backend sortieren lassen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingMode']['0'] = "Gruppenmodus";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingMode']['1'] = "Wenn Sie Einträge ausgehend von diesem Feld im TL Backend gruppieren möchten, wählen Sie einen der Gruppenmodi aus.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['parentCheckbox']['0'] = "Kontroll-Checkbox";
$GLOBALS['TL_LANG']['tl_catalog_fields']['parentCheckbox']['1'] = "Bitte wählen Sie eine Checkbox aus. Das derzeitige Feld wird nur sichtbar sein, wenn die ausgewählte Checkbox angehakt ist.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['mandatory']['0'] = "Pflichtfeld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['mandatory']['1'] = "Ob der Benutzer das Feld ausfüllen muss.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uniqueItem']['0'] = "Eindeutig";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uniqueItem']['1'] = "Ob das Feld eindeutig in der Tabelle ist.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['defValue']['0'] = "Standardwert";
$GLOBALS['TL_LANG']['tl_catalog_fields']['defValue']['1'] = "Bitte geben Sie den Standardwert des Feldes ein.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['minValue']['0'] = "Minimum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['minValue']['1'] = "Legt den Minimalwert fest, den der Benutzer eingeben kann.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['maxValue']['0'] = "Maximum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['maxValue']['1'] = "Legt den Maximalwert fest, den der Benutzer eingeben kann.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['rte']['0'] = "Rich Text";
$GLOBALS['TL_LANG']['tl_catalog_fields']['rte']['1'] = "Falls ausgewählt, wird der Rich Text Editor angezeigt.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTable']['0'] = "Tabelle für Optionen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTable']['1'] = "Bitte wählen Sie eine Tabelle für die Speicherung der Optionen aus.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableIdCol']['0'] = "Spalte für Tabellen-ID";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableIdCol']['1'] = "Bitte wählen Sie eine Spalte für die Tabellen-ID aus.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableValueCol']['0'] = "Spalte für Tabellenwert";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableValueCol']['1'] = "Bitte wählen Sie eine Spalte für die Speicherung einer Option aus.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['limitItems']['0'] = "Auswahl der Einträge";
$GLOBALS['TL_LANG']['tl_catalog_fields']['limitItems']['1'] = "Erlaubt Ihnen verfügbare Optionen für das Feld auszuwählen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['items']['0'] = "Optionen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['items']['1'] = "Bitte wählen Sie jede Option aus, die Sie für das Feld verfügbar machen möchten.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['childrenSelMode']['0'] = "Modus für Unter-Auswahl";
$GLOBALS['TL_LANG']['tl_catalog_fields']['childrenSelMode']['1'] = "Falls ausgewählt, sind Unter-Auswahlen für das Feld verfügbar";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemSortCol']['0'] = "Anzeigen der Sortierspalte";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemSortCol']['1'] = "Bitte wählen Sie eine Spalte aus, in der die Optionen sortiert angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['includeTime']['0'] = "Zeiteingabe";
$GLOBALS['TL_LANG']['tl_catalog_fields']['includeTime']['1'] = "Falls ausgewählt, darf der Benutzer Datum und Zeit eingeben.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['format']['0'] = "Format";
$GLOBALS['TL_LANG']['tl_catalog_fields']['format']['1'] = "Falls ausgewählt, wird der Wert mit einer der ausgewählten Format-Funktionen formatiert.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunction']['0'] = "Formattyp";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunction']['1'] = "Legt fest, welche Format-Funktionen verwendet werden.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatStr']['0'] = "Zeichenfolge für Formatierung";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatStr']['1'] = "Die Zeichenfolge für die Formatierung wird in der Format-Funktion verwendet. Lesen Sie dazu bitte in der Referenz der PHP Funktionen sprintf, number_Format, money_format und date nach.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showLink']['0'] = "Link erzeugen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showLink']['1'] = "Falls ausgewählt, kann der Benutzer den Link zum Download der Datei oder zur Vollansicht des Bildes (Lightbox) anklicken.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showImage']['0'] = "Bild anzeigen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showImage']['1'] = "Falls ausgewählt, wird eine Miniansicht für Bilddateien erstellt.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageWidth']['0'] = "Breite der Miniansicht";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageWidth']['1'] = "Geben Sie die Breite der Miniansicht ein.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageHeight']['0'] = "Höhe der Miniansicht";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageHeight']['1'] = "Geben Sie die Höhe der Miniansicht ein.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['multiple']['0'] = "Mehrere Dateien";
$GLOBALS['TL_LANG']['tl_catalog_fields']['multiple']['1'] = "Falls ausgewählt, kann der Benutzer mehr als eine Daten auswählen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['customFiletree']['0'] = "Ändern des Dateibaumes";
$GLOBALS['TL_LANG']['tl_catalog_fields']['customFiletree']['1'] = "Erlaubt Ihnen, individuelle Optionen für den Dateibaum zu setzen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uploadFolder']['0'] = "Setzen des Ordners für das Wurzelverzeichnis";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uploadFolder']['1'] = "Wählt den Startpunkt, von dem aus der Benutzer dieses Dateifeld auswählt.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['validFileTypes']['0'] = "Gültige Dateitypen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['validFileTypes']['1'] = "Bitte geben Sie eine Komma-separierte Liste mit Erweiterungen für gültige Dateitypen für dieses Feld ein.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filesOnly']['0'] = "Nur Dateien erlauben";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filesOnly']['1'] = "Wählen Sie diese Optionen, um den Dateibrowser einzuschränken, nur Dateien zuzulassen (Ordner sind dann nicht auswählbar).";
$GLOBALS['TL_LANG']['tl_catalog_fields']['taxonomyRoot']['0'] = "Taxonomiezweig";
$GLOBALS['TL_LANG']['tl_catalog_fields']['taxonomyRoot']['1'] = "Bitte wählen Sie den Startpunkt des Taxonomiezweiges aus.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemsTitle'] = "Tabelle: %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['0'] = "Nicht gruppieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['1'] = "Gruppieren anhand des Anfangsbuchstabens und aufsteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['2'] = "Gruppieren anhand des Anfangsbuchstabens und absteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['3'] = "Gruppieren anhand der ersten zwei Buchstaben und aufsteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['4'] = "Gruppieren anhand der ersten zwei Buchstaben und absteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['5'] = "Gruppieren nach Tag und aufsteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['6'] = "Gruppieren nach Tag und absteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['7'] = "Gruppieren nach Monat und aufsteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['8'] = "Gruppieren nach Monat und absteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['9'] = "Gruppieren nach Jahr und aufsteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['10'] = "Gruppieren nach Jahr und absteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['11'] = "Gruppieren und aufsteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['12'] = "Gruppieren und absteigend sortieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['number'] = "Nummer";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['decimal'] = "Dezimal";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['text'] = "Text";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['longtext'] = "Langtext";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['select'] = "Auswahl";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['tags'] = "Tags";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['checkbox'] = "Checkbox";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['url'] = "URL";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['file'] = "Datei";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['taxonomy'] = "Taxonomie";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['alias'] = "Alias";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['string'] = "Zeichenkette";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['number'] = "Nummer";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['money'] = "Geld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['new']['0'] = "Neues Feld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['new']['1'] = "Neues Feld erstellen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['edit']['0'] = "Feld bearbeiten";
$GLOBALS['TL_LANG']['tl_catalog_fields']['edit']['1'] = "Feld ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_catalog_fields']['copy']['0'] = "Feld kopieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['copy']['1'] = "Feld ID %s kopieren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['cut']['0'] = "Feld verschieben";
$GLOBALS['TL_LANG']['tl_catalog_fields']['cut']['1'] = "Feld ID %s verschieben";
$GLOBALS['TL_LANG']['tl_catalog_fields']['delete']['0'] = "Feld löschen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['delete']['1'] = "Feld ID %s löschen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['show']['0'] = "Feld-Eigenschaften";
$GLOBALS['TL_LANG']['tl_catalog_fields']['show']['1'] = "Eigenschaften des Feldes ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['editheader']['0'] = "Eintragstyp bearbeiten";
$GLOBALS['TL_LANG']['tl_catalog_fields']['editheader']['1'] = "Eintragstyp bearbeiten";
 
?>
