<?php
/**
 * TL_ROOT/system/modules/isotope/languages/de/tl_user_group.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user_group']['catalogs']['0'] = "Katalogtypen";
$GLOBALS['TL_LANG']['tl_user_group']['catalogs']['1'] = "Bitte wählen Sie die Katalogtypen aus, die Sie für die Benutzergruppe aktivieren möchten.";
 
?>
