<?php
/**
 * TL_ROOT/system/modules/isotope/languages/ru/default.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['tableExists'] = "Таблица `%s` уже существует. Пожалуйста, выберите другое название.";
$GLOBALS['TL_LANG']['ERR']['tableDoesNotExist'] = "Таблица `%s` не существует.";
$GLOBALS['TL_LANG']['ERR']['columnExists'] = "Колонка `%s` уже существует. Пожалуйста, выберите другое название.";
$GLOBALS['TL_LANG']['ERR']['columnDoesNotExist'] = "Колонка `%s` не существует в таблице %s.";
$GLOBALS['TL_LANG']['ERR']['systemColumn'] = "Имя `%s` зарезервировано для системного использования. Пожалуйста, выберите другое имя.";
$GLOBALS['TL_LANG']['ERR']['invalidColumnName'] = "Неверное название колонки `%s`. Пожалуйста, используйте только буквы, цифры и символ подчеркивания.";
$GLOBALS['TL_LANG']['ERR']['invalidTableName'] = "Неверное название таблицы `%s`. Пожалуйста, используйте только буквы, цифры и символ подчеркивания.";
$GLOBALS['TL_LANG']['ERR']['aliasTitleMissing'] = "Неверная конфигурация алиаса области. Отсутствует параметр название поля.";
$GLOBALS['TL_LANG']['ERR']['aliasDuplicate'] = "Алиас поля `%s` уже определен. Допускается только один алиас на таблицу.";
 
?>
