<?php
/**
 * TL_ROOT/system/modules/isotope/languages/ru/modules.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['catalog']['0'] = "Каталог";
$GLOBALS['TL_LANG']['MOD']['catalog']['1'] = "Модуль позволит вам создать каталог элементов и управлять им.";
$GLOBALS['TL_LANG']['FMD']['catalogListing']['0'] = "Список каталогов";
$GLOBALS['TL_LANG']['FMD']['catalogListing']['1'] = "Используйте модуль для перечисления элементов каталога во внешнем интерфейсе вашего сайта.";
 
?>
