<?php
/**
 * TL_ROOT/system/modules/isotope/languages/ru/tl_catalog_fields.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_fields']['name']['0'] = "Метка";
$GLOBALS['TL_LANG']['tl_catalog_fields']['name']['1'] = "Поле метка, используется для описания области.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['description']['0'] = "Описание";
$GLOBALS['TL_LANG']['tl_catalog_fields']['description']['1'] = "Показывается при входе, предоставляя справочную информацию пользователям.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['colName']['0'] = "Название колонки";
$GLOBALS['TL_LANG']['tl_catalog_fields']['colName']['1'] = "Название колонки в таблице базы данных.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['type']['0'] = "Тип";
$GLOBALS['TL_LANG']['tl_catalog_fields']['type']['1'] = "Тип поля.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['titleField']['0'] = "Отображать в списке просмотра панели управления";
$GLOBALS['TL_LANG']['tl_catalog_fields']['titleField']['1'] = "Это позволяет полям, отображаться в списке просмотра панели управления (также требуется для отображения пользовательских строк).";
$GLOBALS['TL_LANG']['tl_catalog_fields']['aliasTitle']['0'] = "Алиас поля название";
$GLOBALS['TL_LANG']['tl_catalog_fields']['aliasTitle']['1'] = "Пожалуйста, выберите название области, которое будет использоваться для автоматической генерации алиаса.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filteredField']['0'] = "Включить фильтр панели управления";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filteredField']['1'] = "Эта опция добавит фильтр в панель управления, в котором будут перечислены все поля.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['insertBreak']['0'] = "Вставить разрыв";
$GLOBALS['TL_LANG']['tl_catalog_fields']['insertBreak']['1'] = "Создает разрыв между полями для улучшения визуальной группировки.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['searchableField']['0'] = "Включить поиск в панели управления";
$GLOBALS['TL_LANG']['tl_catalog_fields']['searchableField']['1'] = "Эта опция добавит поиск в панель управления";
$GLOBALS['TL_LANG']['tl_catalog_fields']['sortingField']['0'] = "Включить раскрывающуюся сортировку";
$GLOBALS['TL_LANG']['tl_catalog_fields']['sortingField']['1'] = "Эта опция добавит раскрывающуюся сортировку в панель управления";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingMode']['0'] = "Режим сортировки";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingMode']['1'] = "Если вы хотите отсортировать элементы в панели управления TL по этой области, выберите один из способов группировки.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['parentCheckbox']['0'] = "Управляющий чек-бокс";
$GLOBALS['TL_LANG']['tl_catalog_fields']['parentCheckbox']['1'] = "Пожалуйста, выберите чек-бокс. Текущее поле скрыто для редактирования, пока выбранный чек-бокс не отмечен.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['mandatory']['0'] = "Принудительно";
$GLOBALS['TL_LANG']['tl_catalog_fields']['mandatory']['1'] = "Определяет, обязан ли пользователь заполнять поле.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uniqueItem']['0'] = "Уникально";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uniqueItem']['1'] = "Определяет, уникально ли это поле в пределах таблицы.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['defValue']['0'] = "Значение по умолчанию";
$GLOBALS['TL_LANG']['tl_catalog_fields']['defValue']['1'] = "Пожалуйста, введите значение по умолчанию для этого поля.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['minValue']['0'] = "Минимум";
$GLOBALS['TL_LANG']['tl_catalog_fields']['minValue']['1'] = "Определяет минимальное значение, которое может ввести пользователь.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['maxValue']['0'] = "Максимум";
$GLOBALS['TL_LANG']['tl_catalog_fields']['maxValue']['1'] = "Определяет максимальное значение, которое может ввести пользователь.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['rte']['0'] = "Сложный текст";
$GLOBALS['TL_LANG']['tl_catalog_fields']['rte']['1'] = "Если выбрано, будет показан редактор сложного текста.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTable']['0'] = "Исходная таблица настроек";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTable']['1'] = "Пожалуйста, выберите таблицу, где будут сохранены опции.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableIdCol']['0'] = "id колонка";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableIdCol']['1'] = "Пожалуйста, выберите id колонку таблицы.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableValueCol']['0'] = "Колонка значения";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableValueCol']['1'] = "Пожалуйста, выберите колонку, сохраняющую описание опции.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['limitItems']['0'] = "Выбор элементов";
$GLOBALS['TL_LANG']['tl_catalog_fields']['limitItems']['1'] = "Позволяет выбрать доступные опции полей.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['items']['0'] = "Настройки";
$GLOBALS['TL_LANG']['tl_catalog_fields']['items']['1'] = "Пожалуйста, выберите опции, которые хотите сделать доступными для поля.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['childrenSelMode']['0'] = "Режим выбора дочерних записей";
$GLOBALS['TL_LANG']['tl_catalog_fields']['childrenSelMode']['1'] = "Если выбрано, дочерние записи выбранных узлов будут доступны для поля.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemSortCol']['0'] = "Вывод сортировки колонок";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemSortCol']['1'] = "Пожалуйста, выберите столбец, для сортировки опций если показано.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['includeTime']['0'] = "Включая время";
$GLOBALS['TL_LANG']['tl_catalog_fields']['includeTime']['1'] = "Если выбрано, пользователь может ввести дату и время.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['format']['0'] = "Формат";
$GLOBALS['TL_LANG']['tl_catalog_fields']['format']['1'] = "Если выбрано, значение будет отформатировано, используя одну из выбранных функций форматирования.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunction']['0'] = "Тип формата";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunction']['1'] = "Определяет, какое форматирование функции будет использоваться.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatStr']['0'] = "Форматирование строки";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatStr']['1'] = "Форматирование строки будет использоваться в функции форматирования. См. справочную информацию функций php functions sprintf, number_format, money_format и date соответственно.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showLink']['0'] = "Создайть ссылку";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showLink']['1'] = "Если выбрано, пользователь сможет нажать на ссылку, для загрузки файла или полноэкранного показа изображения.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showImage']['0'] = "Вывод изображения";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showImage']['1'] = "Если выбрано, для графических файлов будет создан эскиз.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageWidth']['0'] = "Ширина эскиза";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageWidth']['1'] = "Введите ширину эскиза.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageHeight']['0'] = "Высота эскиза";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageHeight']['1'] = "Введите высоту эскиза.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['multiple']['0'] = "Множественные файлы";
$GLOBALS['TL_LANG']['tl_catalog_fields']['multiple']['1'] = "Если выбрано, пользователь сможет выбрать больше чем один файл.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['customFiletree']['0'] = "Настройка дерева файлов";
$GLOBALS['TL_LANG']['tl_catalog_fields']['customFiletree']['1'] = "Позволит вам установить выборочные опции дерева файлов.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uploadFolder']['0'] = "Назначить файл корневой папки";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uploadFolder']['1'] = "Выберете корень, от которого пользователь выберет поле файла.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['validFileTypes']['0'] = "Правильные типы файла";
$GLOBALS['TL_LANG']['tl_catalog_fields']['validFileTypes']['1'] = "Пожалуйста, введите разделяемый запятой список расширений типов файлов для этого поля.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filesOnly']['0'] = "Разрешить только файлы";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filesOnly']['1'] = "Выберите эту опцию, для ограничения средства просмотра файлов только этими файлами (папки не выбирамые).";
$GLOBALS['TL_LANG']['tl_catalog_fields']['taxonomyRoot']['0'] = "Корень таксономии";
$GLOBALS['TL_LANG']['tl_catalog_fields']['taxonomyRoot']['1'] = "Пожалуйста, выберите корень дерева таксономии.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemsTitle'] = "Таблица: %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['0'] = "Не группировать";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['1'] = "Группировать по начальному символу, в порядке возрастания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['2'] = "Группировать по начальному символу, в порядке убывания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['3'] = "Группировать по двум начальным символами, в порядке возрастания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['4'] = "Группировать по двум начальным символами, в порядке убывания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['5'] = "Группировать по дням, в порядке возрастания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['6'] = "Группировать по дням, в порядке убывания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['7'] = "Группировать по месяцу, в порядке возрастания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['8'] = "Группировать по месяцу, в порядке убывания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['9'] = "Группировать по году, в порядке возрастания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['10'] = "Группировать по году, в порядке убывания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['11'] = "Группировать в порядке возрастания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['12'] = "Группировать в порядке убывания";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['number'] = "Число";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['decimal'] = "Десятичное число";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['text'] = "Текст";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['longtext'] = "Длинный текст";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['date'] = "Дата";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['select'] = "Выбор";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['tags'] = "Теги";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['checkbox'] = "Чек-бокс";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['url'] = "URL";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['file'] = "Файл";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['taxonomy'] = "Таксономия";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['alias'] = "Алиас";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['string'] = "Строка";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['number'] = "Номер";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['money'] = "Деньги";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['date'] = "Дата";
$GLOBALS['TL_LANG']['tl_catalog_fields']['new']['0'] = "Новое поле";
$GLOBALS['TL_LANG']['tl_catalog_fields']['new']['1'] = "Создать новое поле.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['edit']['0'] = "Редактировать поле";
$GLOBALS['TL_LANG']['tl_catalog_fields']['edit']['1'] = "Редактировать поле ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['copy']['0'] = "Копировать поле";
$GLOBALS['TL_LANG']['tl_catalog_fields']['copy']['1'] = "Копировать поле ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['cut']['0'] = "Перенести поле";
$GLOBALS['TL_LANG']['tl_catalog_fields']['cut']['1'] = "Перенести поле ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['delete']['0'] = "Удалить поле";
$GLOBALS['TL_LANG']['tl_catalog_fields']['delete']['1'] = "Удалить поле ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['show']['0'] = "Детали поля";
$GLOBALS['TL_LANG']['tl_catalog_fields']['show']['1'] = "Показать детали о поле ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['editheader']['0'] = "Редактировать тип элемента";
$GLOBALS['TL_LANG']['tl_catalog_fields']['editheader']['1'] = "Редактировать тип элемента";
 
?>
