<?php
/**
 * TL_ROOT/system/modules/isotope/languages/ru/tl_catalog_items.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_items']['export']['0'] = "Экспорт в CSV";
$GLOBALS['TL_LANG']['tl_catalog_items']['export']['1'] = "Экспорт элементов в CSV файл";
$GLOBALS['TL_LANG']['tl_catalog_items']['new']['0'] = "Новый элемент";
$GLOBALS['TL_LANG']['tl_catalog_items']['new']['1'] = "Создать новый элемент.";
$GLOBALS['TL_LANG']['tl_catalog_items']['edit']['0'] = "Редактировать элемент";
$GLOBALS['TL_LANG']['tl_catalog_items']['edit']['1'] = "Редактировать элемент ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['copy']['0'] = "Копировать элемент";
$GLOBALS['TL_LANG']['tl_catalog_items']['copy']['1'] = "Копировать элемент ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['cut']['0'] = "Перенести элемент";
$GLOBALS['TL_LANG']['tl_catalog_items']['cut']['1'] = "Перенести элемент ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['delete']['0'] = "Удалить элемент";
$GLOBALS['TL_LANG']['tl_catalog_items']['delete']['1'] = "Удалить элемент ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['show']['0'] = "Детали элемента";
$GLOBALS['TL_LANG']['tl_catalog_items']['show']['1'] = "Показать детали о элементе ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['editheader']['0'] = "Редактировать тип элемента";
$GLOBALS['TL_LANG']['tl_catalog_items']['editheader']['1'] = "Редактировать тип элемента";
 
?>
