<?php
/**
 * TL_ROOT/system/modules/isotope/languages/ru/tl_user.php 
 * 
 * TYPOlight extension: catalog 0.3.5 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['catalogs']['0'] = "Типы каталогов";
$GLOBALS['TL_LANG']['tl_user']['catalogs']['1'] = "Пожалуйста, выберите типы каталогов, которые хотите включить для пользователя.";
 
?>
