<?php
/**
 * TL_ROOT/system/modules/isotope/languages/nl/default.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['tableExists'] = "Tabel `%s` bestaat al. Kies een andere naam.";
$GLOBALS['TL_LANG']['ERR']['tableDoesNotExist'] = "Tabel `%s` bestaat niet.";
$GLOBALS['TL_LANG']['ERR']['columnExists'] = "Kolom `%s` bestaat al. Kies een andere naam.";
$GLOBALS['TL_LANG']['ERR']['columnDoesNotExist'] = "Kolom `%s` bestaat niet in tabel %s.";
$GLOBALS['TL_LANG']['ERR']['systemColumn'] = "Naam `%s` is gereserveerd voor het systeem. Kies een andere naam.";
$GLOBALS['TL_LANG']['ERR']['invalidColumnName'] = "Ongeldige naam voor kolom `%s`. Gebruik alleen letters, cijfers en underscores.";
$GLOBALS['TL_LANG']['ERR']['invalidTableName'] = "Ongeldige naam voor tabel `%s`. Gebruik alleen letters, cijfers en underscores.";
$GLOBALS['TL_LANG']['ERR']['aliasTitleMissing'] = "Ongeldige alias veld configuratie. Missende titel veld parameter.";
$GLOBALS['TL_LANG']['ERR']['aliasDuplicate'] = "Alias veld `%s` bestaat al. Per tabel is slechts één alias veld toegestaan.";
 
?>
