<?php
/**
 * TL_ROOT/system/modules/isotope/languages/nl/modules.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['catalog']['0'] = "Catalogus";
$GLOBALS['TL_LANG']['MOD']['catalog']['1'] = "Deze module geeft u de mogelijkheid catalogi te definiëren en te beheren.";
$GLOBALS['TL_LANG']['FMD']['catalogListing']['0'] = "Cataloguslijst";
$GLOBALS['TL_LANG']['FMD']['catalogListing']['1'] = "Gebruik deze module om in het frontend cataloguslijsten te maken.";
 
?>
