<?php
/**
 * TL_ROOT/system/modules/isotope/languages/nl/tl_catalog_fields.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_fields']['name']['0'] = "Label";
$GLOBALS['TL_LANG']['tl_catalog_fields']['name']['1'] = "Dit label wordt gebruikt om het veld te beschrijven.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['description']['0'] = "Beschrijving";
$GLOBALS['TL_LANG']['tl_catalog_fields']['description']['1'] = "Tekst die onder het input veld wordt getoond om uitleg te bieden.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['colName']['0'] = "Kolomnaam";
$GLOBALS['TL_LANG']['tl_catalog_fields']['colName']['1'] = "Naam van de kolom in de databasetabel.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['type']['0'] = "Type";
$GLOBALS['TL_LANG']['tl_catalog_fields']['type']['1'] = "Veldtype.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['titleField']['0'] = "Titelveld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['titleField']['1'] = "Indien geselecteerd zal deze waarde beschouwd worden als titel van het catalogus-item en weergegeven worden in de lijst.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['aliasTitle']['0'] = "Alias titelveld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['aliasTitle']['1'] = "Selecteer het titelveld dat gebruikt moet worden voor het maken van de alias.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filteredField']['0'] = "Filter";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filteredField']['1'] = "Indien geselecteerd zal het mogelijk zijn om de weergave van de catalogus-items te regelen d.m.v. een veldwaarde in het backend.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['insertBreak']['0'] = "Voeg een regeleinde in voor dit veld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['insertBreak']['1'] = "Voegt een regeleinde in tussen velden voor een betere groepering van de velden.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['searchableField']['0'] = "Zoek";
$GLOBALS['TL_LANG']['tl_catalog_fields']['searchableField']['1'] = "Indien geselecteerd worden catalogus-items weergegeven die beantwoorden aan bepaalde zoekcriteria in het backend.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['sortingField']['0'] = "Sorteren";
$GLOBALS['TL_LANG']['tl_catalog_fields']['sortingField']['1'] = "Indien geselecteerd worden in het backend weergegeven catalogus-items gesorteerd op basis van dit veld.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingMode']['0'] = "Manier van groeperen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingMode']['1'] = "Als u catalogus-items wil groeperen op basis van dit veld, kies hier dan de manier van groeperen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['parentCheckbox']['0'] = "Vinkje verplicht";
$GLOBALS['TL_LANG']['tl_catalog_fields']['parentCheckbox']['1'] = "Selecteer een checkbox. Dit veld zal alleen zichtbaar zijn voor de gebruiker als deze checkbox is aangevinkt.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['mandatory']['0'] = "Verplicht";
$GLOBALS['TL_LANG']['tl_catalog_fields']['mandatory']['1'] = "De gebruiker is verplicht dit veld in te vullen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uniqueItem']['0'] = "Uniek";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uniqueItem']['1'] = "Dit veld moet uniek zijn in de databasetabel.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['defValue']['0'] = "Default-waarde";
$GLOBALS['TL_LANG']['tl_catalog_fields']['defValue']['1'] = "Voer een default-waarde voor dit veld in.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['minValue']['0'] = "Minimum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['minValue']['1'] = "Geeft de minimale waarde die de gebruiker mag invoeren.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['maxValue']['0'] = "Maximum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['maxValue']['1'] = "Geeft de maximale waarde die de gebruiker mag invoeren.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['rte']['0'] = "Rich text editor";
$GLOBALS['TL_LANG']['tl_catalog_fields']['rte']['1'] = "Indien geselecteerd wordt de rich text editor weergegeven in het veld.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTable']['0'] = "Brontabel opties";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTable']['1'] = "Selecteer de tabel, waarin de opties van dit veld zijn opgeslagen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableIdCol']['0'] = "Tabel ID kolom";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableIdCol']['1'] = "Selecteer een ID kolom van de tabel";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableValueCol']['0'] = "Tabel waarde kolom";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableValueCol']['1'] = "Selecteer een kolom, waarin de beschrijving van een optie is opgeslagen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['limitItems']['0'] = "Selecteer items";
$GLOBALS['TL_LANG']['tl_catalog_fields']['limitItems']['1'] = "Geeft de mogelijkheid beschikbare opties voor het veld te selecteren.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['items']['0'] = "Opties";
$GLOBALS['TL_LANG']['tl_catalog_fields']['items']['1'] = "Selecteer elke optie die voor dit veld beschikbaar moet zijn.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['childrenSelMode']['0'] = "Children selectie mode";
$GLOBALS['TL_LANG']['tl_catalog_fields']['childrenSelMode']['1'] = "Indien geselecteerd zijn children van de geselecteerde nodes beschikbaar voor dit veld.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemSortCol']['0'] = "Geef sorteerkolom weer";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemSortCol']['1'] = "Selecteer een kolom om de opties te sorteren als ze weergegeven worden.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['includeTime']['0'] = "Voeg datum en tijd toe";
$GLOBALS['TL_LANG']['tl_catalog_fields']['includeTime']['1'] = "Indien geselecteerd kan de gebruiker datum en tijd invoeren.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['format']['0'] = "Formatteer";
$GLOBALS['TL_LANG']['tl_catalog_fields']['format']['1'] = "Indien geselecteerd zal de waarde geformatteerd worden volgens een van de geselecteerde formatteer-functies.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunction']['0'] = "Formatteer-type";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunction']['1'] = "Specificeert de formatteer-functie die gebruikt zal worden.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatStr']['0'] = "Formatteer-string";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatStr']['1'] = "Formatteer-string die gebruikt zal worden in de formatteer-functie. Bekijk de handleiding voor de PHP functies <em>sprintf</em>, <em>number_format</em>, <em>money_format</em> of <em>date</em>.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showLink']['0'] = "Maak een hyperlink";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showLink']['1'] = "Indien geselecteerd kan de gebruiker de link aanklikken om het bestand te downloaden of het beeld fullscreen te tonen (Lightbox).";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showImage']['0'] = "Toon beeld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showImage']['1'] = "Indien geselecteerd wordt een thumbnail gemaakt voor beeldbestanden.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageWidth']['0'] = "Breedte thumbnail";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageWidth']['1'] = "Geef de breedte van de thumbnail.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageHeight']['0'] = "Hoogte thumbnail";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageHeight']['1'] = "Geef de hoogte van de thumbnail.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['multiple']['0'] = "Meerdere bestanden";
$GLOBALS['TL_LANG']['tl_catalog_fields']['multiple']['1'] = "Indien geselecteerd kan de gebruiker meer dan één bestand selecteren.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['customFiletree']['0'] = "Verander de File Tree";
$GLOBALS['TL_LANG']['tl_catalog_fields']['customFiletree']['1'] = "Maakt het mogelijk eigen opties aan de File Tree te geven.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uploadFolder']['0'] = "Bepaal de root van bestand";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uploadFolder']['1'] = "Selecteer de root vanaf waar de gebruiker dit bestandsveld zal kiezen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['validFileTypes']['0'] = "Geldige bestandstypes";
$GLOBALS['TL_LANG']['tl_catalog_fields']['validFileTypes']['1'] = "Geef een door komma's gescheiden lijst van toegestane extensies van bestanden voor dit bestandsveld.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filesOnly']['0'] = "Sta alleen bestanden toe";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filesOnly']['1'] = "Indien geselecteerd kan de file browser alleen bestanden selecteren en geen mappen.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['taxonomyRoot']['0'] = "Taxonomy root";
$GLOBALS['TL_LANG']['tl_catalog_fields']['taxonomyRoot']['1'] = "Kies de root van de taxonomy tree.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemsTitle'] = "Tabel: %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['0'] = "Niet groeperen";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['1'] = "Groepeer op eerste letter en sorteer oplopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['2'] = "Groepeer op eerste letter en sorteer aflopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['3'] = "Groepeer op eerste twee letters en sorteer oplopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['4'] = "Groepeer op eerste twee letters en sorteer aflopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['5'] = "Groepeer op dag en sorteer oplopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['6'] = "Groepeer op dag en sorteer aflopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['7'] = "Groepeer op maand en sorteer oplopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['8'] = "Groepeer op maand en sorteer aflopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['9'] = "Groepeer op jaar en sorteer oplopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['10'] = "Groepeer op jaar en sorteer aflopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['11'] = "Groepeer en sorteer oplopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['12'] = "Groepeer en sorteer aflopend";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['number'] = "Nummer";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['decimal'] = "Decimaal";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['text'] = "Tekst (één regel)";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['longtext'] = "Lange tekst (tekstvak)";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['select'] = "Selecteer";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['tags'] = "Tags";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['checkbox'] = "Checkbox";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['url'] = "URL";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['file'] = "Bestand";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['taxonomy'] = "Taxonomy";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['alias'] = "Alias";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['string'] = "String";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['number'] = "Nummer";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['money'] = "Geld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['new']['0'] = "Nieuw veld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['new']['1'] = "Maak een nieuw veld.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['edit']['0'] = "Bewerk veld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['edit']['1'] = "Bewerk veld ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['copy']['0'] = "Kopieer veld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['copy']['1'] = "Kopieer veld ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['cut']['0'] = "Verplaats veld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['cut']['1'] = "Verplaats veld ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['delete']['0'] = "Wis veld";
$GLOBALS['TL_LANG']['tl_catalog_fields']['delete']['1'] = "Wis veld ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['show']['0'] = "Veld details";
$GLOBALS['TL_LANG']['tl_catalog_fields']['show']['1'] = "Toon details van veld ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['editheader']['0'] = "Bewerk item type";
$GLOBALS['TL_LANG']['tl_catalog_fields']['editheader']['1'] = "Bewerk het type van het catalogus-item";
 
?>
