<?php
/**
 * TL_ROOT/system/modules/isotope/languages/nl/tl_catalog_types.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_types']['name']['0'] = "Naam";
$GLOBALS['TL_LANG']['tl_catalog_types']['name']['1'] = "Naam van de catalogus.";
$GLOBALS['TL_LANG']['tl_catalog_types']['tableName']['0'] = "Tabelnaam";
$GLOBALS['TL_LANG']['tl_catalog_types']['tableName']['1'] = "Naam van de databasetabel waarin de catalogus-items worden bewaard.";
$GLOBALS['TL_LANG']['tl_catalog_types']['noTable']['0'] = "Onafhankelijke tabel";
$GLOBALS['TL_LANG']['tl_catalog_types']['noTable']['1'] = "Indien geselecteerd wordt de databasetabel niet ge-update als velden in de catalogus worden toegevoegd of verwijderd. Dit is handig voor het bewerken van bestaande tabellen.";
$GLOBALS['TL_LANG']['tl_catalog_types']['addImage']['0'] = "Voeg beeld toe";
$GLOBALS['TL_LANG']['tl_catalog_types']['addImage']['1'] = "Indien geselecteerd wordt een plaatje toegevoegd aan de vermelding van deze catalogus.";
$GLOBALS['TL_LANG']['tl_catalog_types']['singleSRC']['0'] = "Beeldbestand";
$GLOBALS['TL_LANG']['tl_catalog_types']['singleSRC']['1'] = "Selecteer het beeld dat bij de vermelding van de catalogus geplaatst moet worden.";
$GLOBALS['TL_LANG']['tl_catalog_types']['size']['0'] = "Beeld breedte en hoogte";
$GLOBALS['TL_LANG']['tl_catalog_types']['size']['1'] = "Geef breedte en/of hoogte van het beeld om de maat van het plaatje te veranderen. Als de velden leeg blijven, worden de oorspronkelijke maten gebruikt.";
$GLOBALS['TL_LANG']['tl_catalog_types']['format']['0'] = "Format title string";
$GLOBALS['TL_LANG']['tl_catalog_types']['format']['1'] = "Geef de format string voor elk catalogus-item (niet verplicht). Beelden ondersteunen resize en checkbox beelden worden weergegeven indien TRUE.<br /><strong>Voorbeeld:</strong> <br /><em>&lt;strong&gt;{‎{title_field}}&lt;/strong&gt; &lt;em&gt;({‎{alias_field}})&lt;/em&gt; {‎{checkbox_field::src=imagefile.gif}} {‎{checkbox_field}}&lt;br /&gt;<br />{‎{image_field::w=100&h=80}}</em>";
$GLOBALS['TL_LANG']['tl_catalog_types']['new']['0'] = "Nieuwe catalogus";
$GLOBALS['TL_LANG']['tl_catalog_types']['new']['1'] = "Maak een nieuwe catalogus.";
$GLOBALS['TL_LANG']['tl_catalog_types']['edit']['0'] = "Beheer items";
$GLOBALS['TL_LANG']['tl_catalog_types']['edit']['1'] = "Beheer de items van catalogus ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['copy']['0'] = "Kopieer catalogus definitie";
$GLOBALS['TL_LANG']['tl_catalog_types']['copy']['1'] = "Kopieer de definitie van catalogus ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['delete']['0'] = "Wis catalogus";
$GLOBALS['TL_LANG']['tl_catalog_types']['delete']['1'] = "Wis catalogus ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['show']['0'] = "Catalogus details";
$GLOBALS['TL_LANG']['tl_catalog_types']['show']['1'] = "Toon de details van catalogus ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['editheader']['0'] = "Bewerk catalogus";
$GLOBALS['TL_LANG']['tl_catalog_types']['editheader']['1'] = "Bewerk de catalogus.";
$GLOBALS['TL_LANG']['tl_catalog_types']['fields']['0'] = "Bepaal velden";
$GLOBALS['TL_LANG']['tl_catalog_types']['fields']['1'] = "Bepaal de databasevelden voor catalogus ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['regenerateDca']['0'] = "Regenereer DCA";
$GLOBALS['TL_LANG']['tl_catalog_types']['regenerateDca']['1'] = "Regenereer DCA voor alle catalogi.";
$GLOBALS['TL_LANG']['tl_catalog_types']['itemFormat'] = "<span style=\"color:#b3b3b3;\"><em>(%s %s)</em></span>";
$GLOBALS['TL_LANG']['tl_catalog_types']['itemSingle'] = "item";
$GLOBALS['TL_LANG']['tl_catalog_types']['itemPlural'] = "items";
$GLOBALS['TL_LANG']['tl_catalog_types']['regenerateDcaExplanation'] = "TYPOlight's data container array (DCA) bepaalt hoe de formulieren in het backend weergegeven moeten worden. Het DCA wordt in principe automatisch door deze module bijgewerkt. Toch kan het voorkomen dat de module en het DCA niet meer synchroon zijn. Dit kan bijvoorbeeld gebeuren nadat een nieuwe versie van Catalogus is geïnstalleerd. Druk in dat geval op de knop hieronder om uw catalogi te synchroniseren met TYPOlight.";
$GLOBALS['TL_LANG']['tl_catalog_types']['regenerateDcaSuccess'] = "Gelukt. TYPOlight's data container array (DCA) is opnieuw gegenereerd.";
 
?>
