<?php
/**
 * TL_ROOT/system/modules/isotope/languages/nl/tl_catalog_items.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_items']['export']['0'] = "CSV export";
$GLOBALS['TL_LANG']['tl_catalog_items']['export']['1'] = "Exporteer gegevens van de items naar een CSV bestand";
$GLOBALS['TL_LANG']['tl_catalog_items']['new']['0'] = "Nieuw item";
$GLOBALS['TL_LANG']['tl_catalog_items']['new']['1'] = "Maak een nieuw catalogus-item";
$GLOBALS['TL_LANG']['tl_catalog_items']['edit']['0'] = "Bewerk item";
$GLOBALS['TL_LANG']['tl_catalog_items']['edit']['1'] = "Bewerk catalogus-item ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['copy']['0'] = "Kopieer item";
$GLOBALS['TL_LANG']['tl_catalog_items']['copy']['1'] = "Kopieer catalogus-item ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['cut']['0'] = "Verplaats item";
$GLOBALS['TL_LANG']['tl_catalog_items']['cut']['1'] = "Verplaats catalogus-item ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['delete']['0'] = "Wis item";
$GLOBALS['TL_LANG']['tl_catalog_items']['delete']['1'] = "Wis catalogus-item ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['show']['0'] = "Item details";
$GLOBALS['TL_LANG']['tl_catalog_items']['show']['1'] = "Toon details van catalogus-item ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['editheader']['0'] = "Bewerk item type";
$GLOBALS['TL_LANG']['tl_catalog_items']['editheader']['1'] = "Bewerk het type catalogus-item";
 
?>
