<?php
/**
 * TL_ROOT/system/modules/isotope/languages/fr/default.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['tableExists'] = "La table `%s` existe déjà. Veuillez choisir un nom différent.";
$GLOBALS['TL_LANG']['ERR']['tableDoesNotExist'] = "La table `%s` n'existe pas.";
$GLOBALS['TL_LANG']['ERR']['columnExists'] = "La colonne `%s` existe déjà. Veuillez choisir un nom différent.";
$GLOBALS['TL_LANG']['ERR']['columnDoesNotExist'] = "La colonne `%s` n'existe pas dans la table %s.";
$GLOBALS['TL_LANG']['ERR']['systemColumn'] = "Le nom %s est réservé au système. Veuillez choisir un nom différent.";
$GLOBALS['TL_LANG']['ERR']['invalidColumnName'] = "Le nom de la colonne `%s` n'est pas valide. Utilisez seulement des lettres, nombres et tiret bas.";
$GLOBALS['TL_LANG']['ERR']['invalidTableName'] = "Le nom de la table `%s` n'est pas valide. Utilisez seulement des lettres, nombres et tiret bas.";
$GLOBALS['TL_LANG']['ERR']['aliasTitleMissing'] = "La configuration du champ alias est incorrecte. Le paramètre \"Champ Titre\" est manquant.";
$GLOBALS['TL_LANG']['ERR']['aliasDuplicate'] = "Le champ Alias `%s` est déjà définit. Seulement un champ alias est autorisé par table.";
 
?>
