<?php
/**
 * TL_ROOT/system/modules/isotope/languages/fr/modules.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['catalog']['0'] = "Catalogue";
$GLOBALS['TL_LANG']['MOD']['catalog']['1'] = "Ce module permet de gérer un catalogue d'éléments.";
$GLOBALS['TL_LANG']['FMD']['catalogListing']['0'] = "Liste d'éléments du catalogue";
$GLOBALS['TL_LANG']['FMD']['catalogListing']['1'] = "Utilisez ce module pour lister les éléments d'un catalogue dans le front-office.";
 
?>
