<?php
/**
 * TL_ROOT/system/modules/isotope/languages/fr/tl_catalog_fields.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_fields']['name']['0'] = "Nom";
$GLOBALS['TL_LANG']['tl_catalog_fields']['name']['1'] = "Nom du champ";
$GLOBALS['TL_LANG']['tl_catalog_fields']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_catalog_fields']['description']['1'] = "Description du champ. S'affiche sous le champ de saisie pour afficher une aide ou une description..";
$GLOBALS['TL_LANG']['tl_catalog_fields']['colName']['0'] = "Nom de la colonne";
$GLOBALS['TL_LANG']['tl_catalog_fields']['colName']['1'] = "Nom de la colonne dans la table de la base de données.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['type']['0'] = "Type";
$GLOBALS['TL_LANG']['tl_catalog_fields']['type']['1'] = "Type de champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['titleField']['0'] = "Champ titre";
$GLOBALS['TL_LANG']['tl_catalog_fields']['titleField']['1'] = "Si coché, valeur de champ sera considéré comme titre et sera affiché dans la liste.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['aliasTitle']['0'] = "Champ titre servant d'alias";
$GLOBALS['TL_LANG']['tl_catalog_fields']['aliasTitle']['1'] = "Choisissez le champ titre qui sera utilisé pour l'auto-génération de l'alias.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filteredField']['0'] = "Filtre";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filteredField']['1'] = "Si coché, vous serez en mesure de filtrer les éléments affichés en fonction de valeur du champ dans le back office.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['insertBreak']['0'] = "Insérer une séparation";
$GLOBALS['TL_LANG']['tl_catalog_fields']['insertBreak']['1'] = "Crée une séparation entre les champs pour un meilleur groupement visuel.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['searchableField']['0'] = "Recherche";
$GLOBALS['TL_LANG']['tl_catalog_fields']['searchableField']['1'] = "Si coché, vous serez en mesure d'afficher uniquement les éléments correspondant à des critères de recherche dans le back office.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['sortingField']['0'] = "Tri";
$GLOBALS['TL_LANG']['tl_catalog_fields']['sortingField']['1'] = "Si coché, vous serez en mesure de trier les éléments affichés dans le back office en fonction de ce champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingMode']['0'] = "Méthode de groupement";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingMode']['1'] = "Si vous souhaitez regrouper les éléments dans le back office selon ce champ, sélectionnez l'un des modes de groupement.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['parentCheckbox']['0'] = "Case à cocher de contrôle";
$GLOBALS['TL_LANG']['tl_catalog_fields']['parentCheckbox']['1'] = "Veuillez sélectionner une case à cocher. Le champ courant sera visible seulement si la case à cocher sélectionnée est cochée.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['mandatory']['0'] = "Obligatoire";
$GLOBALS['TL_LANG']['tl_catalog_fields']['mandatory']['1'] = "L'utilisateur devra obligatoirement remplir ce champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uniqueItem']['0'] = "Unique";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uniqueItem']['1'] = "Ce champ est unique dans la table de la base de données.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['defValue']['0'] = "Valeur par défaut";
$GLOBALS['TL_LANG']['tl_catalog_fields']['defValue']['1'] = "Veuillez saisir une valeur par défaut pour le champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['minValue']['0'] = "Minimum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['minValue']['1'] = "Indique la valeur minimale que l'utilisateur peut saisir.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['maxValue']['0'] = "Maximum";
$GLOBALS['TL_LANG']['tl_catalog_fields']['maxValue']['1'] = "Indique la valeur maximale que l'utilisateur peut saisir.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['rte']['0'] = "Texte riche";
$GLOBALS['TL_LANG']['tl_catalog_fields']['rte']['1'] = "Si sélectionné, l'éditeur de texte riche sera affiché.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTable']['0'] = "Table contenant les options";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTable']['1'] = "Veuillez sélectionner une table où seront stockées les options.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableIdCol']['0'] = "Colonne ID de la table";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableIdCol']['1'] = "Veuillez sélectionner une colonne ID de la table.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableValueCol']['0'] = "Colonne de la table contenant les valeurs";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemTableValueCol']['1'] = "Veuillez sélectionner une colonne où est stockée la description d'une option.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['limitItems']['0'] = "Selection des options";
$GLOBALS['TL_LANG']['tl_catalog_fields']['limitItems']['1'] = "Vous permet de sélectionner les options disponibles pour le champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['items']['0'] = "Options";
$GLOBALS['TL_LANG']['tl_catalog_fields']['items']['1'] = "Sélectionnez toutes les options que vous voulez avoir de disponibles pour le champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['childrenSelMode']['0'] = "Sélection des enfants";
$GLOBALS['TL_LANG']['tl_catalog_fields']['childrenSelMode']['1'] = "Si sélectionné, les enfants des nœuds sélectionnés seront disponibles pour le champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemSortCol']['0'] = "Afficher une colonne de tri";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemSortCol']['1'] = "Choisissez une colonne pour trier les options lors de l'affichage.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['includeTime']['0'] = "Saisie de l'heure";
$GLOBALS['TL_LANG']['tl_catalog_fields']['includeTime']['1'] = "Si sélectionné, l'utilisateur peut saisir la date et l'heure.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['format']['0'] = "Formatage";
$GLOBALS['TL_LANG']['tl_catalog_fields']['format']['1'] = "Si sélectionné, la valeur sera formatée à l'aide de l'une des fonctions de mise en forme choisie.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunction']['0'] = "Type de formatage";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunction']['1'] = "Spécifie la fonction de formatage qui sera utilisée.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatStr']['0'] = "Chaine de formatage";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatStr']['1'] = "Chaine de formatage à utiliser dans une fonction de formatage. Voir respectivement la référence des fonctions PHP sprintf, number_format, money_format et date.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showLink']['0'] = "Créer un lien";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showLink']['1'] = "Si cette option est sélectionnée, l'utilisateur sera en mesure de cliquer sur le lien pour télécharger le fichier.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showImage']['0'] = "Afficher l'image";
$GLOBALS['TL_LANG']['tl_catalog_fields']['showImage']['1'] = "Si cette option est sélectionnée, une vignette sera créé pour les images.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageWidth']['0'] = "Largeur de la vignette";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageWidth']['1'] = "Saisissez la largeur de la vignette.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageHeight']['0'] = "Hauteur de la vignette";
$GLOBALS['TL_LANG']['tl_catalog_fields']['imageHeight']['1'] = "Saisissez la hauteur de la vignette.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['multiple']['0'] = "Fichiers multiples";
$GLOBALS['TL_LANG']['tl_catalog_fields']['multiple']['1'] = "Si cette option est sélectionnée, l'utilisateur sera en mesure de sélectionner plus d'un fichier.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['customFiletree']['0'] = "Personnaliser l'arborescence des fichiers";
$GLOBALS['TL_LANG']['tl_catalog_fields']['customFiletree']['1'] = "Vous permet de définir des options personnalisées pour l'arborescence des fichiers.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uploadFolder']['0'] = "Définir le dossier racine";
$GLOBALS['TL_LANG']['tl_catalog_fields']['uploadFolder']['1'] = "Sélectionner un répertoire racine à partir duquel l'utilisateur pourra sélectionner un ou plusieurs fichiers.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['validFileTypes']['0'] = "Types de fichiers valides";
$GLOBALS['TL_LANG']['tl_catalog_fields']['validFileTypes']['1'] = "Veuillez saisir une liste séparée par des virgules, des extensions de fichiers allouées pour ce champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filesOnly']['0'] = "Autoriser seulement les fichiers";
$GLOBALS['TL_LANG']['tl_catalog_fields']['filesOnly']['1'] = "Sélectionnez cette option pour limiter l'explorateur de fichiers aux fichiers seulement (les répertoires ne seront pas sélectionnables).";
$GLOBALS['TL_LANG']['tl_catalog_fields']['taxonomyRoot']['0'] = "Racine d'une classification";
$GLOBALS['TL_LANG']['tl_catalog_fields']['taxonomyRoot']['1'] = "Choisisser la racine d'une classification (Taxonomie)";
$GLOBALS['TL_LANG']['tl_catalog_fields']['itemsTitle'] = "Table : %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['0'] = "Ne pas grouper";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['1'] = "Grouper par la première lettre et tri ascendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['2'] = "Grouper par la première lettre et tri descendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['3'] = "Grouper par les 2 premières lettres et tri ascendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['4'] = "Grouper par les 2 premières lettres et tri descendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['5'] = "Grouper par jour et tri ascendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['6'] = "Grouper par jour et tri descendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['7'] = "Grouper par mois et tri ascendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['8'] = "Grouper par mois et tri descendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['9'] = "Grouper par année et tri ascendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['10'] = "Grouper par année et tri descendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['11'] = "Grouper et tri ascendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['groupingModeOptions']['12'] = "Grouper et tri descendant";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['number'] = "Nombre";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['decimal'] = "Décimal";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['text'] = "Texte";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['longtext'] = "Texte long";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['date'] = "Date";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['select'] = "Liste déroulante";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['tags'] = "Mots clés";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['checkbox'] = "Case à cocher";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['url'] = "URL";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['file'] = "Fichier";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['taxonomy'] = "Classification";
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['alias'] = "Alias";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['string'] = "Chaine de caractères";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['number'] = "Nombre";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['money'] = "Monétaire";
$GLOBALS['TL_LANG']['tl_catalog_fields']['formatFunctionOptions']['date'] = "Date";
$GLOBALS['TL_LANG']['tl_catalog_fields']['new']['0'] = "Nouveau champ";
$GLOBALS['TL_LANG']['tl_catalog_fields']['new']['1'] = "Créer un nouveau champ.";
$GLOBALS['TL_LANG']['tl_catalog_fields']['edit']['0'] = "Editer le champ";
$GLOBALS['TL_LANG']['tl_catalog_fields']['edit']['1'] = "Editer le champ ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['copy']['0'] = "Copier le champ";
$GLOBALS['TL_LANG']['tl_catalog_fields']['copy']['1'] = "Copier le champ ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['cut']['0'] = "Déplacer le champ";
$GLOBALS['TL_LANG']['tl_catalog_fields']['cut']['1'] = "Déplacer le champ ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['delete']['0'] = "Supprimer le champ";
$GLOBALS['TL_LANG']['tl_catalog_fields']['delete']['1'] = "Supprimer le champ ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['show']['0'] = "Détails du champ";
$GLOBALS['TL_LANG']['tl_catalog_fields']['show']['1'] = "Afficher les détails du champ ID %s";
$GLOBALS['TL_LANG']['tl_catalog_fields']['editheader']['0'] = "Editer le type de l'élément";
$GLOBALS['TL_LANG']['tl_catalog_fields']['editheader']['1'] = "Editer le type de l'élément en cours";
 
?>
