<?php
/**
 * TL_ROOT/system/modules/isotope/languages/fr/tl_catalog_types.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_types']['name']['0'] = "Nom";
$GLOBALS['TL_LANG']['tl_catalog_types']['name']['1'] = "Nom du catalogue.";
$GLOBALS['TL_LANG']['tl_catalog_types']['tableName']['0'] = "Nom de la table";
$GLOBALS['TL_LANG']['tl_catalog_types']['tableName']['1'] = "Nom de la table de la base de données où seront stockés les éléments.";
$GLOBALS['TL_LANG']['tl_catalog_types']['noTable']['0'] = "Table indépendante";
$GLOBALS['TL_LANG']['tl_catalog_types']['noTable']['1'] = "Si coché la table de la base de données ne sera pas mis à jour lors de l'ajout ou la suppression de champs du catalogue. Utiles pour l'édition de tables existantes.";
$GLOBALS['TL_LANG']['tl_catalog_types']['addImage']['0'] = "Ajouter une image";
$GLOBALS['TL_LANG']['tl_catalog_types']['addImage']['1'] = "Si vous choisissez cette option, une image sera ajoutée à la liste des catalogues.";
$GLOBALS['TL_LANG']['tl_catalog_types']['singleSRC']['0'] = "Image";
$GLOBALS['TL_LANG']['tl_catalog_types']['singleSRC']['1'] = "Choisissez l'image à afficher dans la liste des catalogues.";
$GLOBALS['TL_LANG']['tl_catalog_types']['size']['0'] = "Largeur et hauteur de l'image";
$GLOBALS['TL_LANG']['tl_catalog_types']['size']['1'] = "Saisissez soit la largeur, la hauteur de l'image ou les deux mesures visant à redimensionner l'image. Si vous laissez les deux champs vides, la taille de l'image originale sera affichée.";
$GLOBALS['TL_LANG']['tl_catalog_types']['format']['0'] = "Chaine de formatage du titre";
$GLOBALS['TL_LANG']['tl_catalog_types']['format']['1'] = "Saisissez une chaine de formatage pour chaque élément du catalogue (Optionnel). Les images supportent le redimensionnement.<br /><strong>Exemple :</strong> <br /><em>{ {title_field} } ({ {alias_field} }) { {checkbox_field::src=imagefile.gif} } { {checkbox_field} }<br />{ {image_field::w=100&h=80} }</em>";
$GLOBALS['TL_LANG']['tl_catalog_types']['new']['0'] = "Nouveau catalogue";
$GLOBALS['TL_LANG']['tl_catalog_types']['new']['1'] = "Créer un nouveau catalogue.";
$GLOBALS['TL_LANG']['tl_catalog_types']['edit']['0'] = "Gérer les éléments";
$GLOBALS['TL_LANG']['tl_catalog_types']['edit']['1'] = "Gérer les éléments du catalogue ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['copy']['0'] = "Copier le catalogue";
$GLOBALS['TL_LANG']['tl_catalog_types']['copy']['1'] = "Copier le catalogue ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['delete']['0'] = "Supprimer le catalogue";
$GLOBALS['TL_LANG']['tl_catalog_types']['delete']['1'] = "Supprimer le catalogue ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['show']['0'] = "Détails du catalogue";
$GLOBALS['TL_LANG']['tl_catalog_types']['show']['1'] = "Afficher les détails du catalogue ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['editheader']['0'] = "Editer le catalogue";
$GLOBALS['TL_LANG']['tl_catalog_types']['editheader']['1'] = "Editer le catalogue";
$GLOBALS['TL_LANG']['tl_catalog_types']['fields']['0'] = "Définir les champs";
$GLOBALS['TL_LANG']['tl_catalog_types']['fields']['1'] = "Définir les champs du catalogue ID %s";
$GLOBALS['TL_LANG']['tl_catalog_types']['regenerateDca']['0'] = "Regénérer le DCA";
$GLOBALS['TL_LANG']['tl_catalog_types']['regenerateDca']['1'] = "Regénérer le DCA (Data Container Array) pour tous les catalogues";
$GLOBALS['TL_LANG']['tl_catalog_types']['itemFormat'] = "<span style=\"color:#b3b3b3;\"><em>(%s %s)</em></span>";
$GLOBALS['TL_LANG']['tl_catalog_types']['itemSingle'] = "élément";
$GLOBALS['TL_LANG']['tl_catalog_types']['itemPlural'] = "éléments";
$GLOBALS['TL_LANG']['tl_catalog_types']['regenerateDcaExplanation'] = "Le \"Data Container Array\" (DCA) de TYPOlight permet à TYPOlight de créer les formulaires du back-office. Afin de fournir un moyen pratique d'éditer les éléments de votre catalogue dans le back-office, le module Catalogue crée le DCA automatiquement. Mais parfois le DCA et votre catalogue ne sont plus synchronisés, par exemple après l'installation d'une nouvelle version du module Catalogue. Dans ce cas, utilisez le bouton \"Régénérer DCA\" ci-dessous pour synchroniser vos catalogues avec TYPOlight.";
$GLOBALS['TL_LANG']['tl_catalog_types']['regenerateDcaSuccess'] = "Le \"Data Container Array\" (DCA) de TYPOlight a été regénéré avec succès.";
 
?>
