<?php
/**
 * TL_ROOT/system/modules/isotope/languages/fr/tl_catalog_items.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_items']['export']['0'] = "Export CSV";
$GLOBALS['TL_LANG']['tl_catalog_items']['export']['1'] = "Exporte les éléments dans un fichier CSV";
$GLOBALS['TL_LANG']['tl_catalog_items']['new']['0'] = "Nouvel élément";
$GLOBALS['TL_LANG']['tl_catalog_items']['new']['1'] = "Créer un nouvel élément.";
$GLOBALS['TL_LANG']['tl_catalog_items']['edit']['0'] = "Editer l'élément";
$GLOBALS['TL_LANG']['tl_catalog_items']['edit']['1'] = "Editer l'élément ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['copy']['0'] = "Copier l'élément";
$GLOBALS['TL_LANG']['tl_catalog_items']['copy']['1'] = "Copier l'élément ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['cut']['0'] = "Déplacer l'élément";
$GLOBALS['TL_LANG']['tl_catalog_items']['cut']['1'] = "Déplacer l'élément ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['delete']['0'] = "Supprimer l'élément";
$GLOBALS['TL_LANG']['tl_catalog_items']['delete']['1'] = "Supprimer l'élément ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['show']['0'] = "Détails de l'élément";
$GLOBALS['TL_LANG']['tl_catalog_items']['show']['1'] = "Afficher les détails de l'élément ID %s";
$GLOBALS['TL_LANG']['tl_catalog_items']['editheader']['0'] = "Editer le catalogue";
$GLOBALS['TL_LANG']['tl_catalog_items']['editheader']['1'] = "Editer le catalogue";
 
?>
