<?php
/**
 * TL_ROOT/system/modules/isotope/languages/fr/tl_user.php 
 * 
 * TYPOlight extension: catalog 0.3.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['catalogs']['0'] = "Catalogues";
$GLOBALS['TL_LANG']['tl_user']['catalogs']['1'] = "Veuillez choisir les catalogues que vous voulez activer pour l'utilisateur.";
 
?>
